spring:
  data:
    mongodb:
      username: sammy
      password: sammy123
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090

